<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\DataLayer\Event\BeginCheckout as BeginCheckoutEvent;
use Yireo\GoogleTagManager2LokiCheckout\Component\GoogleTagManagerViewModel;

/** @var Template $block */
/** @var BeginCheckoutEvent $beginCheckoutEvent */
/** @var GoogleTagManagerViewModel $viewModel */
?>
<div style="display:none">
</div>
