<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\GoogleTagManager2\DataLayer\Event\BeginCheckout as BeginCheckoutEvent;
use Yireo\GoogleTagManager2LokiCheckout\Component\Checkout as CheckoutComponent;

/** @var Template $block */
/** @var BeginCheckoutEvent $beginCheckoutEvent */
/** @var CheckoutComponent $viewModel */
$beginCheckoutEvent = $block->getData('begin_checkout_event');
?>
<div class="hidden">
    <script>
        window.addEventListener('ga:trigger-event', function (event) {
            yireoGoogleTagManager2Pusher(event.detail, 'Loki Checkout');
        });

        (function () {
            yireoGoogleTagManager2Pusher(<?= json_encode($beginCheckoutEvent->get()) ?>, 'Loki Checkout');
        })();
    </script>
</div>
