<script>
    document.addEventListener('loki:init:localstorage-store', () => {
        Alpine.effect(async () => {
            const checkoutSection = await Alpine.store('LocalStorage').get('loki-checkout');
            if (!checkoutSection) {
                return;
            }

            if (!checkoutSection.gtm_events) {
                return;
            }

            checkoutSection.gtm_events.forEach(eventData => {
                if (!eventData) {
                    return;
                }

                eventData = JSON.parse(JSON.stringify(eventData));
                yireoGoogleTagManager2Pusher(eventData, eventData.event);
            });
        });
    });
</script>
