<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiCheckoutGoogleTagManager', () => ({
            ...LokiLoadDataComponentPartial,
            events: [],
            init() {
                this.loadData();
                this.gtmEvents.forEach(eventData => {
                    if (!eventData) {
                        return;
                    }

                    yireoGoogleTagManager2Pusher(this.fromProxyToObject(eventData), eventData.event);
                });
            },
            fromProxyToObject(proxy) {
                return JSON.parse(JSON.stringify(proxy))
            }
        }));
    });
</script>
